### ISSUE TITLE
lien.lien is not a function

### ISSUE THREAD

**Issue by nikhilrayaprolu** [IonicaBizau/youtube-api#61]
```
/home/nikhil/proj/educationtest/ieducative/app/models/coursevideo.js:61
			lien.lien(err, 400);
			     ^

TypeError: lien.lien is not a function
    at /home/nikhil/proj/educationtest/ieducative/app/models/coursevideo.js:61:9
    at /home/nikhil/proj/educationtest/ieducative/node_modules/youtube-api/node_modules/googleapis/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/home/nikhil/proj/educationtest/ieducative/node_modules/youtube-api/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:70:30)
    at self.callback (/home/nikhil/proj/educationtest/ieducative/node_modules/youtube-api/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/nikhil/proj/educationtest/ieducative/node_modules/youtube-api/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:861:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at ClientRequest.onError (/home/nikhil/proj/educationtest/ieducative/node_modules/youtube-api/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/node_modules/tunnel-agent/index.js:178:21)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:312:10)
    at onwrite (_stream_writable.js:330:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:456:13)
    at TLSSocket.Socket._destroy (net.js:497:3)
    at WriteWrap.afterWrite (net.js:787:10)

```
I am getting this error on signing in oauth2

**Comment by IonicaBizau** [comment]
The error comes from your script: `/home/nikhil/proj/educationtest/ieducative/app/models/coursevideo.js:61`.

Replace `lien.lien` with `lien.end`.
