### ISSUE TITLE
Cannot read property 'req' of undefined

### ISSUE THREAD

**Issue by archubbuck** [IonicaBizau/youtube-api#97]
My assumption is that the issue is on my end where I may have improperly configured the client. Please let me know if there is any specific set up that must take place beforehand.

```Adams-MBP:BlueMoonMelodies adam$ node youtube.js 
info  Trying to get the token using the following code: <redacted>
info  Got the tokens.
/Users/adam/Desktop/BlueMoonMelodies/youtube.js:100
            Logger.log(`${prettyBytes(req.req.connection._bytesDispatched)} bytes uploaded.`);
                                          ^

TypeError: Cannot read property 'req' of undefined
    at Timeout._onTimeout (/Users/adam/Desktop/BlueMoonMelodies/youtube.js:100:43)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)```

**Comment by IonicaBizau** [comment]
This may happen because of the latest updates from `googleapis`. We have to check out how they currently expose the `_bytesDispatched` value, more exactly the request object.
